dist: trusty
sudo: required

language: generic

script:
    - docker build -t buildozer .
    - docker run -t buildozer uname -a
    - docker run -t buildozer cython --version
    - docker run -t buildozer buildozer --version