dist: trusty
sudo: required

language: generic

before_script:
    - source scripts/travis_output_helper.sh

script:
    # start loop from travis_output_helper.sh
    - ping_loop

    # create docker image and download all needed andorid dependencies:
    - docker build -t buildozer . >> $BUILD_OUTPUT 2>&1

    - dump_output
    - kill $PING_LOOP_PID

    # Just print some version info:
    - docker run buildozer uname -a
    - docker run buildozer cython --version
    - docker run buildozer buildozer --version

    # List all installed packages:
    - docker run buildozer dpkg-query -l
    - pip freeze

    # try to compile 'kivy_hello_world':
    # We use 'buildozer --verbose' to get better information about build errors.
    - ping_loop
    - docker run -t buildozer -v ${PWD}/kivy_hello_world:/buildozer/ buildozer --verbose android release >> $BUILD_OUTPUT 2>&1
    - dump_output
    - kill $PING_LOOP_PID