dist: trusty
sudo: required

language: generic

before_script:
    - source scripts/travis_output_helper.sh

script:
    # start loop from travis_output_helper.sh
    - start_output_loop

    # create docker image and download all needed andorid dependencies:
    - docker build -t buildozer . >> $BUILD_OUTPUT 2>&1

    - end_output_loop

    # List all installed packages:
    - docker run buildozer pip freeze

    # Just print some version info:
    - docker run buildozer uname -a
    - docker run buildozer cython --version
    - docker run buildozer buildozer --version

after_success:
    - if [ "$TRAVIS_BRANCH" == "master" ]; then
        docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
        docker push jedie/buildozer;
      fi