dist: trusty
sudo: required

language: generic

script:
    - python3 ./manage.py build
    - python3 ./manage.py version_info

after_success:
    - if [ "$TRAVIS_BRANCH" == "master" ]; then
        docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
        docker push jedie/buildozer;
      fi